# Generated by Django 5.2.7 on 2025-10-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcheck_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='role',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
