# Generated by Django 5.2.7 on 2025-10-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcheck_account', '0002_alter_pendinguser_role_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
