# Generated by Django 5.2.7 on 2025-10-22 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcheck_account', '0003_pendinguser_position_profile_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.CharField(help_text='Token provided by PSU OAuth server', max_length=100, unique=True)),
                ('user_email', models.EmailField(help_text='Email associated with this token', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Token expiration date', null=True)),
            ],
        ),
    ]
