# Generated by Django 5.2.7 on 2025-10-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcheck_account', '0004_oauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthtoken',
            name='otp_code',
            field=models.CharField(blank=True, help_text='6-digit OTP code', max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='OTP expiration date', null=True),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='token_key',
            field=models.CharField(blank=True, help_text='Legacy token field', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='user_email',
            field=models.EmailField(help_text='Email associated with this OTP', max_length=254),
        ),
    ]
