# Generated by Django 5.2.7 on 2025-10-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcheck_account', '0005_oauthtoken_otp_code_alter_oauthtoken_expires_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OAuthToken',
        ),
        migrations.RemoveField(
            model_name='pendinguser',
            name='position',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='role',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student'), ('staff', 'Staff')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student'), ('staff', 'Staff')], max_length=20, null=True),
        ),
    ]
