# Generated by Django 5.2.7 on 2025-11-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcheck_account', '0006_delete_oauthtoken_remove_pendinguser_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
