# Generated by Django 5.2.7 on 2025-10-31 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultybooking',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bookings_attachments/'),
        ),
        migrations.CreateModel(
            name='PeripheralEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(choices=[('removed', 'Removed'), ('attached', 'Attached')], max_length=32)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.pc')),
            ],
        ),
    ]
